hugoblox:
  schema: "2.0"
  identity:
    name: The Adaptive Mind
    type: person
    tagline: Exploring the use of AI in teaching and research
    description: ""
  theme:
    mode: system
    pack: retro
    colors:
      primary: ""
      secondary: ""
      neutral: ""
  typography:
    font: serif
    size: md
  layout:
    radius: md
    spacing: comfortable
    avatar_shape: circle
  header:
    enable: true
    style: navbar
    sticky: true
    align: center
    search: true
    theme_toggle: true
    language_switcher: false
    cta:
      enable: false
  footer:
    style: minimal
    language_switcher: true
  copyright:
    notice: © {year} {name}
    license:
      allow_derivatives: true
  content:
    math:
      enable: true
    toc:
      enable: true
    reading_time:
      enable: true
  search:
    enable: true
  seo:
    title: Rafael Libanori | Materials Scientist | ETH Zurich
    location:
      address:
        street: Vladimir-Prelog-Weg 1/5
        city: Zurich
        postal_code: "8093"
        country: Switzerland
  comments:
    enable: false
    provider: disqus
  locale:
    date_format: Jan 2, 2015
    time_format: 22:04h
    address_format: de-ch
  privacy:
    enable: true
